#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Export lenovo-server tenants for VPS migration.

This script reads lenovo.db container records and exports:
- tenant manifest TSV
- per-tenant metadata TSV + env_vars JSON
- per-tenant workspace tar.gz from data/containers/<tenant-id>

Usage:
  export-lenovo-tenants.sh [options]

Options:
  --project-dir <dir>       lenovo-server project root (default: script parent)
  --output-dir <dir>        export destination (default: <project>/backups)
  --provision               Also run VM provisioning per tenant
  --ssh-key-file <path>     Required with --provision
  --bridge <name>           Bridge for VM provisioning (default: br0)
  --admin-user <name>       Admin username for VM provisioning (default: admin)
  --help                    Show help

Examples:
  ./scripts/export-lenovo-tenants.sh
  ./scripts/export-lenovo-tenants.sh --provision --ssh-key-file ~/.ssh/id_ed25519.pub
USAGE
}

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT_DIR=""
PROVISION=false
SSH_KEY_FILE=""
BRIDGE="br0"
ADMIN_USER="admin"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project-dir)
      PROJECT_DIR="$2"
      shift 2
      ;;
    --output-dir)
      OUTPUT_DIR="$2"
      shift 2
      ;;
    --provision)
      PROVISION=true
      shift
      ;;
    --ssh-key-file)
      SSH_KEY_FILE="$2"
      shift 2
      ;;
    --bridge)
      BRIDGE="$2"
      shift 2
      ;;
    --admin-user)
      ADMIN_USER="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if ! command -v sqlite3 >/dev/null 2>&1; then
  echo "sqlite3 command not found" >&2
  exit 1
fi

if [[ "$PROVISION" == true && -z "$SSH_KEY_FILE" ]]; then
  echo "--ssh-key-file is required with --provision" >&2
  exit 1
fi

DB_PATH="$PROJECT_DIR/data/lenovo.db"
if [[ ! -f "$DB_PATH" && -f "$PROJECT_DIR/data/shironeko.db" ]]; then
  DB_PATH="$PROJECT_DIR/data/shironeko.db"
fi
CONTAINERS_DIR="$PROJECT_DIR/data/containers"
PROVISION_SCRIPT="$PROJECT_DIR/scripts/provision-lenovo-vm.sh"

if [[ ! -f "$DB_PATH" ]]; then
  echo "DB not found: $DB_PATH" >&2
  exit 1
fi

if [[ -z "$OUTPUT_DIR" ]]; then
  OUTPUT_DIR="$PROJECT_DIR/backups"
fi

TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
EXPORT_ROOT="${OUTPUT_DIR%/}/lenovo-tenant-export-${TIMESTAMP}"
mkdir -p "$EXPORT_ROOT/tenants" "$EXPORT_ROOT/meta"
MANIFEST="$EXPORT_ROOT/meta/tenant-manifest.tsv"

echo -e "tenant_id\tname\ttype\tplan\tstatus\tssh_username\tstartup_command" > "$MANIFEST"

echo "[1/4] Reading tenant list..."
TMP_ROWS="$(mktemp)"
trap 'rm -f "$TMP_ROWS"' EXIT

HAS_SSH_USERNAME="$(sqlite3 "$DB_PATH" "SELECT COUNT(*) FROM pragma_table_info('containers') WHERE name='ssh_username';")"
HAS_STARTUP_COMMAND="$(sqlite3 "$DB_PATH" "SELECT COUNT(*) FROM pragma_table_info('containers') WHERE name='startup_command';")"
HAS_ENV_VARS="$(sqlite3 "$DB_PATH" "SELECT COUNT(*) FROM pragma_table_info('containers') WHERE name='env_vars';")"

SSH_USERNAME_EXPR="''"
STARTUP_COMMAND_EXPR="''"
ENV_VARS_EXPR="'{}'"
[[ "$HAS_SSH_USERNAME" -gt 0 ]] && SSH_USERNAME_EXPR="COALESCE(ssh_username,'')"
[[ "$HAS_STARTUP_COMMAND" -gt 0 ]] && STARTUP_COMMAND_EXPR="COALESCE(startup_command,'')"
[[ "$HAS_ENV_VARS" -gt 0 ]] && ENV_VARS_EXPR="COALESCE(env_vars,'{}')"

sqlite3 -noheader -separator '|' "$DB_PATH" \
  "SELECT id, name, type, plan, status, ${SSH_USERNAME_EXPR}, ${STARTUP_COMMAND_EXPR}, ${ENV_VARS_EXPR} FROM containers ORDER BY created_at;" > "$TMP_ROWS"

if [[ ! -s "$TMP_ROWS" ]]; then
  echo "No tenants found in containers table"
  exit 0
fi

echo "[2/4] Exporting tenant files..."
while IFS='|' read -r tenant_id name type plan status ssh_username startup_command env_vars; do
  [[ -z "$tenant_id" ]] && continue
  tenant_dir="$EXPORT_ROOT/tenants/$tenant_id"
  mkdir -p "$tenant_dir"

  echo -e "${tenant_id}\t${name}\t${type}\t${plan}\t${status}\t${ssh_username}\t${startup_command}" >> "$MANIFEST"

  # metadata (TSV + raw env JSON to avoid escaping issues)
  cat > "$tenant_dir/metadata.tsv" <<META
tenant_id	${tenant_id}
name	${name}
type	${type}
plan	${plan}
status	${status}
ssh_username	${ssh_username}
startup_command	${startup_command}
META
  printf '%s\n' "$env_vars" > "$tenant_dir/env_vars.json"

  src_dir="$CONTAINERS_DIR/$tenant_id"
  if [[ -d "$src_dir" ]]; then
    tar czf "$tenant_dir/workspace.tar.gz" -C "$src_dir" .
  fi

done < "$TMP_ROWS"

echo "[3/4] Creating recommended provision commands..."
COMMANDS_FILE="$EXPORT_ROOT/meta/provision-commands.sh"
cat > "$COMMANDS_FILE" <<CMDS
#!/usr/bin/env bash
set -euo pipefail
# Generated by export-lenovo-tenants.sh
# Fill in your public key path and run commands one by one.
CMDS

while IFS='|' read -r tenant_id _name _type plan _status _ssh_username _startup_command _env_vars; do
  [[ -z "$tenant_id" ]] && continue
  case "$plan" in
    free)
      memory=1024; vcpus=1; disk=15 ;;
    standard)
      memory=2048; vcpus=2; disk=25 ;;
    pro)
      memory=4096; vcpus=4; disk=40 ;;
    *)
      memory=2048; vcpus=2; disk=20 ;;
  esac

  echo "$PROVISION_SCRIPT --tenant-id $tenant_id --ssh-key-file /path/to/id_ed25519.pub --bridge $BRIDGE --admin-user $ADMIN_USER --memory-mb $memory --vcpus $vcpus --disk-gb $disk" >> "$COMMANDS_FILE"

done < "$TMP_ROWS"
chmod +x "$COMMANDS_FILE"

echo "[4/4] Optional auto-provision..."
if [[ "$PROVISION" == true ]]; then
  while IFS='|' read -r tenant_id _name _type plan _status _ssh_username _startup_command _env_vars; do
    [[ -z "$tenant_id" ]] && continue

    case "$plan" in
      free)
        memory=1024; vcpus=1; disk=15 ;;
      standard)
        memory=2048; vcpus=2; disk=25 ;;
      pro)
        memory=4096; vcpus=4; disk=40 ;;
      *)
        memory=2048; vcpus=2; disk=20 ;;
    esac

    "$PROVISION_SCRIPT" \
      --tenant-id "$tenant_id" \
      --ssh-key-file "$SSH_KEY_FILE" \
      --bridge "$BRIDGE" \
      --admin-user "$ADMIN_USER" \
      --memory-mb "$memory" \
      --vcpus "$vcpus" \
      --disk-gb "$disk"

  done < "$TMP_ROWS"
else
  echo "  - skipped (run with --provision to create VMs now)"
fi

(
  cd "$EXPORT_ROOT"
  find . -type f -print0 | sort -z | xargs -0 sha256sum > SHA256SUMS
)

echo "Export complete: $EXPORT_ROOT"
echo "Manifest: $MANIFEST"
echo "Provision commands: $COMMANDS_FILE"
